amcl:
  ros__parameters:
    use_sim_time:  true

    # Frame names
    map_frame:     map
    odom_frame:    odom
    base_frame:    base_link
    scan_topic:    scan

    # Particle filter
    min_particles:      500
    max_particles:     2000
    kld_err:             0.02
    kld_z:               0.99

    # Sensor model (laser)
    laser_z_hit:         0.5
    laser_sigma_hit:     0.2
    laser_z_rand:        0.5
    laser_likelihood_max_dist: 2.0

    # Update thresholds
    update_min_d:        0.1       # meters
    update_min_a:        0.2       # radians

    # Resample
    resample_interval:   2
