costmap_common:
  ros__parameters:
    footprint: [[-0.3,-0.3],[-0.3,0.3],[0.3,0.3],[0.3,-0.3]]
    robot_radius:         0.3

    # Obstacle layer
    obstacle_range:       2.5
    raytrace_range:       3.0
    inflation_radius:     0.4

    plugins:  
      - {name: static_layer,  type: "nav2_costmap_2d::StaticLayer"}
      - {name: obstacle_layer,type: "nav2_costmap_2d::ObstacleLayer"}
      - {name: inflation_layer,type: "nav2_costmap_2d::InflationLayer"}
