local_costmap:
  ros__parameters:
    use_sim_time:      true
    global_frame:      odom
    robot_base_frame:  base_link
    update_frequency:  5.0
    publish_frequency: 2.0
    rolling_window:    true
    width:             6.0
    height:            6.0

    # include common settings
    plugin_names:      [static_layer, obstacle_layer, inflation_layer]
    plugin_types:  
      ["nav2_costmap_2d::StaticLayer",
       "nav2_costmap_2d::ObstacleLayer",
       "nav2_costmap_2d::InflationLayer"]
