controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["rear_left_joint"]
      right_wheel_names: ["rear_right_joint"]

      wheel_separation: 0.3
      wheel_radius: 0.05

      cmd_vel_timeout: 0.25
      publish_rate: 50

      use_stamped_vel: false

      base_frame_id: base_link
      enable_odom_tf: true

      pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
      twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
