controller_manager:
  ros__parameters:
    update_rate:  100

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  ros__parameters:
    publish_rate: 50

omni_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints: [ wheel1, wheel2, wheel3 ]
    state_publish_rate:  25
    action_monitor_rate: 10
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time:                0.1
    gains:
      wheel1:
        p: 10.0
        d: 0.1
        i: 0.0
        i_clamp: 1.0
      # …repeat for wheel2, wheel3…
