teleop_twist_joy_node:
  ros__parameters:
    use_sim_time: true 
    require_enable_button: true
    enable_button: 4       # L1 hold-to-drive
    enable_turbo_button: 5  # L1 + R1 = turbo (optional)

    # Left stick → linear
    axis_linear.x: 1        # left stick Y
    axis_linear.y: 0        # left stick X
    scale_linear.x: 0.20   # negative so UP gives +x
    scale_linear.y: 0.20   # negative so LEFT gives +y

    # Right stick X → spin
    axis_angular.yaw: 3     # try 2 if your driver maps it there
    scale_angular.yaw: 0.25

    # Turbo scales (optional) ONLY USE FOR NAV NOT MAP
    scale_linear_turbo.x: 0.5
    scale_linear_turbo.y: 0.5
    scale_angular_turbo.yaw: 2.0


    